---
machines:
  bs_web:
    hostname: "bs_web"
    ipv4: "192.168.71.10"
    playbook: "provisioning/ansible/web_server.yml"
    folder_map:
    - guest: "/opt/www"
      host: "../../byng_systems@bitbucket.org/byng-co/"
      owner: www-data
      group: www-data
    port_map:
    - guest: 80
      host: 8080
    - guest: 443
      host: 4443

  bs_db:
    hostname: "bs_db"
    ipv4: "192.168.71.20"
    playbook: "provisioning/ansible/db_server.yml"
